# Generated by Django 4.1.4 on 2022-12-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecategory',
            old_name='course_catagory_name',
            new_name='course_category_name',
        ),
    ]
