# Generated by Django 4.1.2 on 2022-12-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'ordering': ('-date_added',), 'verbose_name': 'Student_course', 'verbose_name_plural': 'Student_courses'},
        ),
        migrations.AlterModelTable(
            name='studentcourse',
            table='student_course',
        ),
    ]
