# Generated by Django 4.1.4 on 2022-12-15 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentcourse_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birth_date',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
